In [ ]:
import numpy as np
import tensorflow as tf
import pandas as pd


In [ ]:
x=np.random.sample((100,2))
dataset=tf.data.Dataset.from_tensor_slices(x)


In [ ]:
dataset

<TensorSliceDataset shapes: (2,), types: tf.float64>

In [ ]:
x[:3]

array([[0.50090327, 0.20648463],
       [0.9913476 , 0.97585325],
       [0.84512168, 0.23857435]])

In [ ]:
for i in dataset:
  print(i)

tf.Tensor([0.50090327 0.20648463], shape=(2,), dtype=float64)
tf.Tensor([0.9913476  0.97585325], shape=(2,), dtype=float64)
tf.Tensor([0.84512168 0.23857435], shape=(2,), dtype=float64)
tf.Tensor([0.17877847 0.21231748], shape=(2,), dtype=float64)
tf.Tensor([0.08773656 0.78461763], shape=(2,), dtype=float64)
tf.Tensor([0.69400716 0.52286003], shape=(2,), dtype=float64)
tf.Tensor([0.99586838 0.22429587], shape=(2,), dtype=float64)
tf.Tensor([0.64924139 0.3475792 ], shape=(2,), dtype=float64)
tf.Tensor([0.90307911 0.17095287], shape=(2,), dtype=float64)
tf.Tensor([0.23697816 0.06389841], shape=(2,), dtype=float64)
tf.Tensor([0.98416461 0.33864936], shape=(2,), dtype=float64)
tf.Tensor([0.73213056 0.70955358], shape=(2,), dtype=float64)
tf.Tensor([0.85287165 0.29537343], shape=(2,), dtype=float64)
tf.Tensor([0.6879256  0.89574806], shape=(2,), dtype=float64)
tf.Tensor([0.18365342 0.88184348], shape=(2,), dtype=float64)
tf.Tensor([0.40342333 0.19925336], shape=(2,), dtype=float64)
tf.Tenso

In [ ]:
features,labels=np.random.randn(100,2),np.random.randn(100,1)


In [ ]:
dataset=tf.data.Dataset.from_tensor_slices((features,labels))

In [ ]:
dataset

<TensorSliceDataset shapes: ((2,), (1,)), types: (tf.float64, tf.float64)>

In [ ]:
for i in dataset:
  print(i)

(<tf.Tensor: shape=(2,), dtype=float64, numpy=array([-0.19661381,  0.12083502])>, <tf.Tensor: shape=(1,), dtype=float64, numpy=array([0.64413813])>)
(<tf.Tensor: shape=(2,), dtype=float64, numpy=array([ 1.06175926, -0.82940054])>, <tf.Tensor: shape=(1,), dtype=float64, numpy=array([-0.54390447])>)
(<tf.Tensor: shape=(2,), dtype=float64, numpy=array([-1.44003316,  0.07900854])>, <tf.Tensor: shape=(1,), dtype=float64, numpy=array([0.07214239])>)
(<tf.Tensor: shape=(2,), dtype=float64, numpy=array([ 0.97142621, -0.39648791])>, <tf.Tensor: shape=(1,), dtype=float64, numpy=array([1.49266765])>)
(<tf.Tensor: shape=(2,), dtype=float64, numpy=array([0.74986875, 0.68182941])>, <tf.Tensor: shape=(1,), dtype=float64, numpy=array([-0.13974036])>)
(<tf.Tensor: shape=(2,), dtype=float64, numpy=array([-0.48335873, -0.61867069])>, <tf.Tensor: shape=(1,), dtype=float64, numpy=array([-0.91007588])>)
(<tf.Tensor: shape=(2,), dtype=float64, numpy=array([ 0.22229839, -0.30315411])>, <tf.Tensor: shape=(1,),

In [ ]:
dataset=tf.data.Dataset.range(10)
for i in dataset:
  print(i)

tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(6, shape=(), dtype=int64)
tf.Tensor(7, shape=(), dtype=int64)
tf.Tensor(8, shape=(), dtype=int64)
tf.Tensor(9, shape=(), dtype=int64)


In [ ]:
a=dataset.as_numpy_iterator()






In [ ]:
list(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
dataset=dataset.batch(3)

In [ ]:
list(dataset.as_numpy_iterator())

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([9])]

In [ ]:
for i in dataset:
  print(i)

tf.Tensor([0 1 2], shape=(3,), dtype=int64)
tf.Tensor([3 4 5], shape=(3,), dtype=int64)
tf.Tensor([6 7 8], shape=(3,), dtype=int64)
tf.Tensor([9], shape=(1,), dtype=int64)


In [ ]:
dataset=dataset.map(lambda x:x*2)

In [ ]:
list(dataset.as_numpy_iterator())

[array([0, 2, 4]), array([ 6,  8, 10]), array([12, 14, 16]), array([18])]

In [ ]:
dataset=tf.data.Dataset.from_tensor_slices([(4,5),(6,8)])
dataset=dataset.enumerate()

In [ ]:
list(dataset.as_numpy_iterator())

[(0, array([4, 5], dtype=int32)), (1, array([6, 8], dtype=int32))]

In [ ]:
for i in dataset:
  print(i)

(<tf.Tensor: shape=(), dtype=int64, numpy=0>, <tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 5], dtype=int32)>)
(<tf.Tensor: shape=(), dtype=int64, numpy=1>, <tf.Tensor: shape=(2,), dtype=int32, numpy=array([6, 8], dtype=int32)>)


# METHODS

In [ ]:
#apply method
dataset = tf.data.Dataset.range(100)
def dataset_fn(ds):
  return ds.filter(lambda x: x < 5)
dataset = dataset.apply(dataset_fn)
list(dataset.as_numpy_iterator())


[0, 1, 2, 3, 4]

In [ ]:
#as_numpy_iterator use when to print each element of dataset (How it will going to look)
#Returns an iterator which converts all elements of the dataset to numpy
dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3])
for i in dataset:
  print(i)
a=dataset.as_numpy_iterator()
print(a)
for i in dataset.as_numpy_iterator() :
  print(i)

print(list(dataset.as_numpy_iterator()))  

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
1
2
3
[1, 2, 3]


In [ ]:
dataset = tf.data.Dataset.from_tensor_slices({'a': ([1, 2], [3, 4]),
                                              'b': [5, 6]})
print(dataset)
for i in dataset:
  print(i)
for i in dataset.as_numpy_iterator() :
  print(i)

<TensorSliceDataset shapes: {a: ((), ()), b: ()}, types: {a: (tf.int32, tf.int32), b: tf.int32}>
{'a': (<tf.Tensor: shape=(), dtype=int32, numpy=1>, <tf.Tensor: shape=(), dtype=int32, numpy=3>), 'b': <tf.Tensor: shape=(), dtype=int32, numpy=5>}
{'a': (<tf.Tensor: shape=(), dtype=int32, numpy=2>, <tf.Tensor: shape=(), dtype=int32, numpy=4>), 'b': <tf.Tensor: shape=(), dtype=int32, numpy=6>}
{'a': (1, 3), 'b': 5}
{'a': (2, 4), 'b': 6}


In [ ]:
dataset = tf.data.Dataset.range(8)
for i in dataset:
  print(i)

tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(6, shape=(), dtype=int64)
tf.Tensor(7, shape=(), dtype=int64)


In [ ]:
#Batch
#The components of the resulting element will have an additional outer dimension, which will be batch_size (or N % batch_size for the last element if batch_size does not divide the number of input elements N evenly and drop_remainder is False).
#If your program depends on the batches having the same outer dimension, you should set the drop_remainder argument to True to prevent the smaller batch from being produced.
dataset = tf.data.Dataset.range(8)
dataset = dataset.batch(3, drop_remainder=True)
for i in dataset:
  print(i)

list(dataset.as_numpy_iterator())


tf.Tensor([0 1 2], shape=(3,), dtype=int64)
tf.Tensor([3 4 5], shape=(3,), dtype=int64)


[array([0, 1, 2]), array([3, 4, 5])]

In [ ]:
#cardinality
#Returns the cardinality of the dataset, if known.

#cardinality may return tf.data.INFINITE_CARDINALITY if the dataset contains an infinite number of elements or tf.data.UNKNOWN_CARDINALITY if the analysis fails to determine the number of elements in the dataset
#(e.g. when the dataset source is a file)

dataset = tf.data.Dataset.range(42)
print(dataset.cardinality().numpy())

dataset = dataset.repeat()
cardinality = dataset.cardinality()
print((cardinality == tf.data.INFINITE_CARDINALITY).numpy())

42
True


In [ ]:
#concatenate
#The input dataset and dataset to be concatenated should have the same
# nested structures and output types.
a = tf.data.Dataset.range(1, 4)  # ==> [ 1, 2, 3 ]
b = tf.data.Dataset.range(4, 8)  # ==> [ 4, 5, 6, 7 ]
ds = a.concatenate(b)
for i in ds:
  print(i)
list(ds.as_numpy_iterator())
print(ds.element_spec)

tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(6, shape=(), dtype=int64)
tf.Tensor(7, shape=(), dtype=int64)
TensorSpec(shape=(), dtype=tf.int64, name=None)


In [ ]:
#enumerate
dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3])
dataset = dataset.enumerate(start=5)
for i in dataset:
  print(i)
for element in dataset.as_numpy_iterator():
  print(element) 

(<tf.Tensor: shape=(), dtype=int64, numpy=5>, <tf.Tensor: shape=(), dtype=int32, numpy=1>)
(<tf.Tensor: shape=(), dtype=int64, numpy=6>, <tf.Tensor: shape=(), dtype=int32, numpy=2>)
(<tf.Tensor: shape=(), dtype=int64, numpy=7>, <tf.Tensor: shape=(), dtype=int32, numpy=3>)
(5, 1)
(6, 2)
(7, 3)


In [ ]:
# The nested structure of the input dataset determines the structure of
# elements in the resulting dataset.
dataset = tf.data.Dataset.from_tensor_slices([(7, 8), (9, 10)])
dataset = dataset.enumerate()
for element in dataset.as_numpy_iterator():
  print(element)

print(dataset.element_spec)  

(0, array([7, 8], dtype=int32))
(1, array([ 9, 10], dtype=int32))
(TensorSpec(shape=(), dtype=tf.int64, name=None), TensorSpec(shape=(2,), dtype=tf.int32, name=None))


In [ ]:
#filter
dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3])
dataset = dataset.filter(lambda x: x < 3)
print(list(dataset.as_numpy_iterator()))

# `tf.math.equal(x, y)` is required for equality comparison
def filter_fn(x):
  return tf.math.equal(x, 1)
dataset = dataset.filter(filter_fn)
print(list(dataset.as_numpy_iterator()))

[1, 2]
[1]


In [ ]:
#flat_map(map_fun)
#Maps map_func across this dataset and flattens the result.

#Use flat_map if you want to make sure that the order of your dataset stays the same. For example, to flatten a dataset of batches into a dataset of their elements:
dataset = tf.data.Dataset.from_tensor_slices(
               [[1, 2, 3], [4, 5, 6], [7, 8, 9]])
for i in dataset:
  print(i)
dataset = dataset.flat_map(lambda x: tf.data.Dataset.from_tensor_slices(x))
for i in dataset:
  print(i)
print(list(dataset.as_numpy_iterator()))

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([4 5 6], shape=(3,), dtype=int32)
tf.Tensor([7 8 9], shape=(3,), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
#from_tensor_slices

#Creates a Dataset whose elements are slices of the given tensors.

#The given tensors are sliced along their first dimension. This operation preserves the structure of the input tensors,
#removing the first dimension of each tensor and using it as the dataset dimension. All input tensors must have the same size in their first dimensions.
#2d array covert to 1d array
#1d array to 0d array
#3d array to 2d array

# Slicing a 1D tensor produces scalar tensor elements.
dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3])
print(list(dataset.as_numpy_iterator()))

# Slicing a 2D tensor produces 1D tensor elements.
dataset = tf.data.Dataset.from_tensor_slices([[1, 2], [3, 4]])
print(dataset.element_spec)
for i in dataset:
  print(i)
print(list(dataset.as_numpy_iterator()))


[1, 2, 3]
TensorSpec(shape=(2,), dtype=tf.int32, name=None)
tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor([3 4], shape=(2,), dtype=int32)
[array([1, 2], dtype=int32), array([3, 4], dtype=int32)]


In [ ]:
# Slicing a tuple of 1D tensors produces tuple elements containing
# scalar tensors.
dataset = tf.data.Dataset.from_tensor_slices(([1, 2], [3, 4], [5, 6]))
print(dataset.element_spec)
for i in dataset:
  print(i)
for i in dataset.as_numpy_iterator():
  print(i)


list(dataset.as_numpy_iterator())


(TensorSpec(shape=(), dtype=tf.int32, name=None), TensorSpec(shape=(), dtype=tf.int32, name=None), TensorSpec(shape=(), dtype=tf.int32, name=None))
(<tf.Tensor: shape=(), dtype=int32, numpy=1>, <tf.Tensor: shape=(), dtype=int32, numpy=3>, <tf.Tensor: shape=(), dtype=int32, numpy=5>)
(<tf.Tensor: shape=(), dtype=int32, numpy=2>, <tf.Tensor: shape=(), dtype=int32, numpy=4>, <tf.Tensor: shape=(), dtype=int32, numpy=6>)
(1, 3, 5)
(2, 4, 6)


[(1, 3, 5), (2, 4, 6)]

In [ ]:
dataset = tf.data.Dataset.from_tensor_slices({"a": [1, 2], "b": [3, 4]})
for i in dataset:
  print(i)
print(dataset.element_spec)
for i in dataset.as_numpy_iterator():
  print(i)
  print(type(i))
list(dataset.as_numpy_iterator())

{'a': <tf.Tensor: shape=(), dtype=int32, numpy=1>, 'b': <tf.Tensor: shape=(), dtype=int32, numpy=3>}
{'a': <tf.Tensor: shape=(), dtype=int32, numpy=2>, 'b': <tf.Tensor: shape=(), dtype=int32, numpy=4>}
{'a': TensorSpec(shape=(), dtype=tf.int32, name=None), 'b': TensorSpec(shape=(), dtype=tf.int32, name=None)}
{'a': 1, 'b': 3}
<class 'dict'>
{'a': 2, 'b': 4}
<class 'dict'>


[{'a': 1, 'b': 3}, {'a': 2, 'b': 4}]

In [ ]:
# Two tensors can be combined into one Dataset object.
features = tf.constant([[1, 3], [2, 1], [3, 3]]) # ==> 3x2 tensor
labels = tf.constant(['A', 'B', 'A']) # ==> 3x1 tensor
dataset = tf.data.Dataset.from_tensor_slices((features, labels))
print(dataset.element_spec)
for i in dataset.as_numpy_iterator():
  print(i)

(TensorSpec(shape=(2,), dtype=tf.int32, name=None), TensorSpec(shape=(), dtype=tf.string, name=None))
(array([1, 3], dtype=int32), b'A')
(array([2, 1], dtype=int32), b'B')
(array([3, 3], dtype=int32), b'A')


In [ ]:
# Both the features and the labels tensors can be converted
# to a Dataset object separately and combined after.
features_dataset = tf.data.Dataset.from_tensor_slices(features)
labels_dataset = tf.data.Dataset.from_tensor_slices(labels)
dataset = tf.data.Dataset.zip((features_dataset, labels_dataset))
print(dataset.element_spec)
for i in dataset.as_numpy_iterator():
  print(i)

(TensorSpec(shape=(2,), dtype=tf.int32, name=None), TensorSpec(shape=(), dtype=tf.string, name=None))
(array([1, 3], dtype=int32), b'A')
(array([2, 1], dtype=int32), b'B')
(array([3, 3], dtype=int32), b'A')


In [ ]:
# A batched feature and label set can be converted to a Dataset
# in similar fashion.
batched_features = tf.constant([[[1, 3], [2, 3]],
                                [[2, 1], [1, 2]],
                                [[3, 3], [3, 2]]], shape=(3, 2, 2))
batched_labels = tf.constant([['A', 'A'],
                              ['B', 'B'],
                              ['A', 'B']], shape=(3, 2, 1))
dataset = tf.data.Dataset.from_tensor_slices((batched_features, batched_labels))
for element in dataset.as_numpy_iterator():
  print(element)
print(dataset.element_spec)


(array([[1, 3],
       [2, 3]], dtype=int32), array([[b'A'],
       [b'A']], dtype=object))
(array([[2, 1],
       [1, 2]], dtype=int32), array([[b'B'],
       [b'B']], dtype=object))
(array([[3, 3],
       [3, 2]], dtype=int32), array([[b'A'],
       [b'B']], dtype=object))
(TensorSpec(shape=(2, 2), dtype=tf.int32, name=None), TensorSpec(shape=(2, 1), dtype=tf.string, name=None))


In [ ]:
#from_tensors
#Creates a Dataset with a single element, comprising the given tensors.

#from_tensors produces a dataset containing only a single element. To slice the input tensor into multiple elements, use from_tensor_slices instead.

dataset = tf.data.Dataset.from_tensors([1, 2, 3])
print(dataset.element_spec)
for i in dataset:
  print(i)
list(dataset.as_numpy_iterator())

TensorSpec(shape=(3,), dtype=tf.int32, name=None)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)


[array([1, 2, 3], dtype=int32)]

In [ ]:
dataset = tf.data.Dataset.from_tensors(([1, 2, 3], 'A'))
list(dataset.as_numpy_iterator())


[(array([1, 2, 3], dtype=int32), b'A')]

In [ ]:
# You can use `from_tensors` to produce a dataset which repeats
# the same example many times.
example = tf.constant([1,2,3])
dataset = tf.data.Dataset.from_tensors(example).repeat(2)
for i in dataset:
  print(i)
list(dataset.as_numpy_iterator())


tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)


[array([1, 2, 3], dtype=int32), array([1, 2, 3], dtype=int32)]

In [ ]:
#Dataset.from_generator

def count(stop):
  i = 0
  while i<stop:
    yield i
    i += 1
for n in count(5):
  print(n)    

0
1
2
3
4


In [ ]:
#The Dataset.from_generator constructor converts the python generator to a fully functional tf.data.Dataset.
#The constructor takes a callable as input, not an iterator. This allows it to restart the generator when it reaches the end.
#It takes an optional args argument, which is passed as the callable's arguments.

#The output_types argument is required because tf.data builds a tf.Graph internally, and graph edges require a tf.dtype.

In [ ]:
ds_counter = tf.data.Dataset.from_generator(count, args=[25], output_types=tf.int32, output_shapes = (), )
for i in ds_counter.as_numpy_iterator():
  print(i)
print(ds_counter.element_spec)
#list(ds_counter.as_numpy_iterator())
for count_batch in ds_counter.repeat().batch(10).take(10):
  print(count_batch.numpy())


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
TensorSpec(shape=(), dtype=tf.int32, name=None)
[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[20 21 22 23 24  0  1  2  3  4]
[ 5  6  7  8  9 10 11 12 13 14]
[15 16 17 18 19 20 21 22 23 24]
[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[20 21 22 23 24  0  1  2  3  4]
[ 5  6  7  8  9 10 11 12 13 14]
[15 16 17 18 19 20 21 22 23 24]


The output_shapes argument is not required but is highly recomended as many tensorflow operations do not support tensors with unknown rank. If the length of a particular axis is unknown or variable, set it as None in the output_shapes.

It's also important to note that the output_shapes and output_types follow the same nesting rules as other dataset methods.

Here is an example generator that demonstrates both aspects, it returns tuples of arrays, where the second array is a vector with unknown length.

In [ ]:
def gen_series():
  i = 0
  while True:
    size = np.random.randint(0, 10)
    yield i, np.random.normal(size=(size,))
    i += 1

In [ ]:
for i, series in gen_series():
  print(i, ":", str(series))
  if i > 5:
    break

0 : [1.39051501]
1 : []
2 : [-0.49274442  1.63050112  0.88110511 -0.90731555  1.12963349]
3 : [-1.10370639  1.73035494 -1.43057084 -1.80784613  1.90160006  0.6642023
 -2.34001654 -0.0554659 ]
4 : [0.04811683]
5 : [0.89335355]
6 : [-2.09944594]


The first output is an int32 the second is a float32.

The first item is a scalar, shape (), and the second is a vector of unknown length, shape (None,)

In [ ]:
ds_series = tf.data.Dataset.from_generator(
    gen_series, 
    output_types=(tf.int32, tf.float32), 
    output_shapes=((), (None,)))
ds_series

<FlatMapDataset shapes: ((), (None,)), types: (tf.int32, tf.float32)>

In [ ]:
for i in ds_series.take(2):
  print(i)

(<tf.Tensor: shape=(), dtype=int32, numpy=0>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([-1.0333077], dtype=float32)>)
(<tf.Tensor: shape=(), dtype=int32, numpy=1>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([-0.68692344], dtype=float32)>)


Now it can be used like a regular tf.data.Dataset. Note that when batching a dataset with a variable shape, you need to use Dataset.padded_batch.

In [ ]:
ds_series_batch = ds_series.shuffle(20).padded_batch(10)

ids, sequence_batch = next(iter(ds_series_batch))
print(ids.numpy())
print()
print(sequence_batch.numpy())

[14  0  1 20 19 21 23 18 10 26]

[[ 0.0501857   0.8191717   1.5689937  -0.78768575 -0.84647137  0.43050388
  -0.065193   -0.18688445  0.13015513]
 [ 0.38477743 -0.7311848   0.          0.          0.          0.
   0.          0.          0.        ]
 [-0.4082313  -1.3019208   0.3639212   0.75554955  1.6721325  -0.6810055
  -1.3524638   1.642166    1.7227256 ]
 [ 0.44087845  0.51906675 -0.410327    0.39807597 -0.2586968   1.1783385
  -1.6329658  -0.72807753  0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.          0.        ]
 [-1.6237085   0.          0.          0.          0.          0.
   0.          0.          0.        ]
 [-0.35042244  1.6083319  -0.38347912 -0.4411754   0.          0.
   0.          0.          0.        ]
 [-1.3432125   0.          0.          0.          0.          0.
   0.          0.          0.        ]
 [-0.43065593 -0.5119627  -1.0290245   0.5075615  -1.5836909   0.93836373
   0.          0.          0.  

In [ ]:
#map(map_func, num_parallel_calls=None, deterministic=None)
#Maps map_func across the elements of this dataset.

#This transformation applies map_func to each element of this dataset, and returns a new dataset containing the transformed elements, in the same order as they appeared in the input.
#map_func can be used to change both the values and the structure of a dataset's elements. For example, adding 1 to each element, or projecting a subset of element components.

# Each element is a tuple containing two `tf.Tensor` objects.
elements = [(1, "foo"), (2, "bar"), (3, "baz")]
dataset = tf.data.Dataset.from_generator(
    lambda: elements, (tf.int32, tf.string))
# `map_func` takes two arguments of type `tf.Tensor`. This function
# projects out just the first component.
result = dataset.map(lambda x_int, y_str: x_int)
list(result.as_numpy_iterator())


[1, 2, 3]

In [ ]:
#padded_batch(batch_size, padded_shapes=None, padding_values=None, drop_remainder=False)


Unlike tf.data.Dataset.batch, the input elements to be batched may have different shapes, and this transformation will pad each component to the respective shape in padded_shapes. The padded_shapes argument determines the resulting shape for each dimension of each component in an output element:

If the dimension is a constant, the component will be padded out to that length in that dimension.

If the dimension is unknown, the component will be padded out to the maximum length of all elements in that dimension.

In [ ]:
A = (tf.data.Dataset
     .range(1, 5, output_type=tf.int32)
     .map(lambda x: tf.fill([x], x)))
for i in A:
  print(i)
# Pad to the smallest per-batch size that fits all elements.
B = A.padded_batch(2)
for element in B.as_numpy_iterator():
  print(element)


tf.Tensor([1], shape=(1,), dtype=int32)
tf.Tensor([2 2], shape=(2,), dtype=int32)
tf.Tensor([3 3 3], shape=(3,), dtype=int32)
tf.Tensor([4 4 4 4], shape=(4,), dtype=int32)
[[1 0]
 [2 2]]
[[3 3 3 0]
 [4 4 4 4]]


In [ ]:
# Pad to a fixed size.
C = A.padded_batch(2, padded_shapes=5)
for element in C.as_numpy_iterator():
  print(element)

[[1 0 0 0 0]
 [2 2 0 0 0]]
[[3 3 3 0 0]
 [4 4 4 4 0]]


In [ ]:
# Pad with a custom value.
D = A.padded_batch(2, padded_shapes=5, padding_values=-1)
for element in D.as_numpy_iterator():
  print(element)

[[ 1 -1 -1 -1 -1]
 [ 2  2 -1 -1 -1]]
[[ 3  3  3 -1 -1]
 [ 4  4  4  4 -1]]


In [ ]:
#range

#Creates a Dataset of a step-separated range of values.

list(tf.data.Dataset.range(5).as_numpy_iterator())

# list(Dataset.range(2, 5).as_numpy_iterator())

# list(Dataset.range(1, 5, 2).as_numpy_iterator())

# list(Dataset.range(1, 5, -2).as_numpy_iterator())

# list(Dataset.range(5, 1).as_numpy_iterator())

# list(Dataset.range(5, 1, -2).as_numpy_iterator())

# list(Dataset.range(2, 5, output_type=tf.int32).as_numpy_iterator())

# list(Dataset.range(1, 5, 2, output_type=tf.float32).as_numpy_iterator())


[0, 1, 2, 3, 4]

In [ ]:
#reduce(initial_state, reduce_func)


Reduces the input dataset to a single element.

The transformation calls reduce_func successively on every element of the input dataset until the dataset is exhausted, aggregating information in its internal state. The initial_state argument is used for the initial state and the final state is returned as the result.

In [ ]:
print(tf.data.Dataset.range(5).reduce(np.int64(0), lambda x, _: x + 1).numpy())

tf.data.Dataset.range(5).reduce(np.int64(0), lambda x, y: x + y).numpy()


5


10

In [ ]:
#repeat(count=None)
#Repeats this dataset so each original value is seen count times.
dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3])
dataset = dataset.repeat(3)
list(dataset.as_numpy_iterator())

[1, 2, 3, 1, 2, 3, 1, 2, 3]

## SHUFFLE

In [ ]:
arr = [1, 2, 3, 4, 5, 6]



In [ ]:
# Simple dataset from the `arr` above
# Just to show how to create the dataset and iterate over it.
import tensorflow as tf

dataset = tf.data.Dataset.from_tensor_slices(arr)

for idx, elem in enumerate(dataset):
  print(f'step #{idx}: {elem.numpy()}')

step #0: 1
step #1: 2
step #2: 3
step #3: 4
step #4: 5
step #5: 6


In [ ]:
# Add shuffling:
# Random buffer
#    |
#    |   Source dataset where all other elements live
#    |         |
#    ↓         ↓
# [1,2,3] <= [4,5,6]
#
# It requires 3 steps for the number 6 to come into the shuffle buffer.
# Therefore, it will be printed only at step 3 (starting from 0) or later.
# But not earlier.
# Re-run this cell (Ctrl + Enter) to check.

dataset = tf.data.Dataset.from_tensor_slices(arr)
dataset = dataset.shuffle(buffer_size=3)

for idx, elem in enumerate(dataset):
  print(f'step #{idx}: {elem.numpy()}')

step #0: 1
step #1: 3
step #2: 4
step #3: 6
step #4: 2
step #5: 5


In [ ]:
# Adding `repeat()`.
# It will make dataset re-initialize after each iteration
# producing indefinite sequence of elements.
# We'll stop after first 10 steps.

dataset = tf.data.Dataset.from_tensor_slices(arr)
dataset = dataset.shuffle(buffer_size=3).repeat()

for idx, elem in enumerate(dataset):
  print(f'step #{idx}: {elem.numpy()}')
  # dataset will be genearted indefinetly,
  # so we'll limit the first 10 elements only
  if idx >= 18:
    break

step #0: 1
step #1: 3
step #2: 5
step #3: 6
step #4: 4
step #5: 2
step #6: 2
step #7: 4
step #8: 3
step #9: 6
step #10: 1
step #11: 5
step #12: 1
step #13: 2
step #14: 3
step #15: 6
step #16: 4
step #17: 5
step #18: 3


In [ ]:
# Now we'll add batching.

dataset = tf.data.Dataset.from_tensor_slices(arr)
dataset = dataset.shuffle(buffer_size=3).repeat().batch(3)

for idx, elem in enumerate(dataset):
  print(f'batch #{idx}: {elem.numpy()}')
  # Dataset will be genearted indefinetly,
  # so we'll limit the first 4 batches only
  if idx >= 3:
    break

batch #0: [2 1 3]
batch #1: [6 4 5]
batch #2: [3 1 5]
batch #3: [2 4 6]


In [ ]:
## Check that the last number (6 in our case)
# won't appear in the first batch

In [ ]:
#shuffle(buffer_size, seed=None, reshuffle_each_iteration=None)

Randomly shuffles the elements of this dataset.

This dataset fills a buffer with buffer_size elements, then randomly samples elements from this buffer, replacing the selected elements with new elements. For perfect shuffling, a buffer size greater than or equal to the full size of the dataset is required.

For instance, if your dataset contains 10,000 elements but buffer_size is set to 1,000, then shuffle will initially select a random element from only the first 1,000 elements in the buffer. Once an element is selected, its space in the buffer is replaced by the next (i.e. 1,001-st) element, maintaining the 1,000 element buffer.

reshuffle_each_iteration controls whether the shuffle order should be different for each epoch. In TF 1.X, the idiomatic way to create epochs was through the **repeat** transformation:

In [ ]:
dataset = tf.data.Dataset.range(3)
dataset = dataset.shuffle(3, reshuffle_each_iteration=True)
dataset = dataset.repeat(2)  # doctest: +SKIP
list(dataset.as_numpy_iterator())

[0, 2, 1, 1, 0, 2]

In [ ]:
dataset = tf.data.Dataset.range(3)
dataset = dataset.shuffle(3, reshuffle_each_iteration=False)
dataset = dataset.repeat(3)  # doctest: +SKIP
list(dataset.as_numpy_iterator())

[2, 0, 1, 2, 0, 1, 2, 0, 1]

In TF 2.0, tf.data.Dataset objects are Python iterables which makes it possible to also create epochs through Python iteration:

In [ ]:
dataset = tf.data.Dataset.range(3)
dataset = dataset.shuffle(3, reshuffle_each_iteration=True)
print(list(dataset.as_numpy_iterator()))  # doctest: +SKIP

print(list(dataset.as_numpy_iterator()) ) # doctest: +SKIP


[1, 2, 0]
[2, 1, 0]


In [ ]:
#skip(count)
#Creates a Dataset that skips count elements from this dataset.
dataset = tf.data.Dataset.range(10)
dataset = dataset.skip(7)
list(dataset.as_numpy_iterator())

[7, 8, 9]

In [ ]:
#take(count)
#Creates a Dataset with at most count elements from this dataset.
dataset = tf.data.Dataset.range(10)
dataset = dataset.take(3)
list(dataset.as_numpy_iterator())


[0, 1, 2]

In [ ]:
#nbatch()
elements = [ [1, 2, 3], [1, 2], [1, 2, 3, 4] ]
dataset = tf.data.Dataset.from_generator(lambda: elements, tf.int64)
for i  in dataset.as_numpy_iterator():
  print(i)
dataset = dataset.unbatch()
list(dataset.as_numpy_iterator())


[1 2 3]
[1 2]
[1 2 3 4]


[1, 2, 3, 1, 2, 1, 2, 3, 4]

Splits elements of a dataset into multiple elements.

For example, if elements of the dataset are shaped [B, a0, a1, ...], where B may vary for each input element, then for each element in the dataset, the unbatched dataset will contain B consecutive elements of shape [a0, a1, ...].

# **zip**

Creates a Dataset by zipping together the given datasets.

This method has similar semantics to the built-in zip() function in Python, with the main difference being that the datasets argument can be an arbitrary nested structure of Dataset objects.

In [ ]:
# The nested structure of the `datasets` argument determines the
# structure of elements in the resulting dataset.
a = tf.data.Dataset.range(1, 4)  # ==> [ 1, 2, 3 ]
b = tf.data.Dataset.range(4, 7)  # ==> [ 4, 5, 6 ]
ds = tf.data.Dataset.zip((a, b))
print(list(ds.as_numpy_iterator()))

ds = tf.data.Dataset.zip((b, a))
print(list(ds.as_numpy_iterator()))


# The `datasets` argument may contain an arbitrary number of datasets.
c = tf.data.Dataset.range(7, 13).batch(2)  # ==> [ [7, 8],
                                           #       [9, 10],
                                           #       [11, 12] ]
ds = tf.data.Dataset.zip((a, b, c))
for element in ds.as_numpy_iterator():
  print(element)




# The number of elements in the resulting dataset is the same as
# the size of the smallest dataset in `datasets`.
d = tf.data.Dataset.range(13, 15)  # ==> [ 13, 14 ]
ds = tf.data.Dataset.zip((a, d))
print(list(ds.as_numpy_iterator()))




[(1, 4), (2, 5), (3, 6)]
[(4, 1), (5, 2), (6, 3)]
(1, 4, array([7, 8]))
(2, 5, array([ 9, 10]))
(3, 6, array([11, 12]))
[(1, 13), (2, 14)]


# **tf.data.Iterator**

In [ ]:
dataset = tf.data.Dataset.range(2)
for element in dataset:
  print(element)



tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)


In [ ]:
#or by fetching individual elements explicitly via get_next():
dataset = tf.data.Dataset.range(2)
iterator = iter(dataset)
print(iterator.get_next())

print(iterator.get_next())


tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
